from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any, Tuple
from datetime import datetime


class TopicRule(BaseModel):
    """Rule for selecting problems from a specific topic."""
    topic: str = Field(..., description="Topic name")
    difficulty_range: Tuple[int, int] = Field(..., description="Difficulty range (min, max) inclusive")
    question_count: int = Field(..., ge=0, description="Number of questions to select for this topic")
    
    class Config:
        json_schema_extra = {
            "example": {
                "topic": "calculus",
                "difficulty_range": [3, 5],
                "question_count": 5
            }
        }


class AssessmentPlan(BaseModel):
    """Plan generated by the planner for assessment creation."""
    strategy: str = Field(..., description="Pedagogical strategy to be used")
    topic_rules: List[TopicRule] = Field(default_factory=list, description="Rules for topic selection")
    time_limit_minutes: int = Field(..., ge=1, description="Total time limit for the assessment")
    reasoning_log: str = Field(..., description="Explanation of planning decisions")
    
    class Config:
        json_schema_extra = {
            "example": {
                "strategy": "progressive_difficulty",
                "topic_rules": [
                    {
                        "topic": "calculus",
                        "difficulty_range": [3, 5],
                        "question_count": 5
                    }
                ],
                "time_limit_minutes": 60,
                "reasoning_log": "Selected progressive difficulty strategy based on student's current level"
            }
        }


class AssessmentRequest(BaseModel):
    """Request for generating an assessment."""
    pedagogical_strategy: Optional[str] = Field(
        default="REVIEW",
        description="Pedagogical strategy: REVIEW, NEW_TOPIC_INTRODUCTION, or CHALLENGE"
    )
    max_total_time_minutes: int = Field(
        ...,
        ge=1,
        description="Maximum total time limit for the assessment in minutes"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "pedagogical_strategy": "NEW_TOPIC_INTRODUCTION",
                "max_total_time_minutes": 60
            }
        }


class SelectedProblem(BaseModel):
    """Problem selected for assessment."""
    id: str = Field(..., description="Problem ID")
    text: str = Field(..., description="Problem text")
    topic: str = Field(..., description="Problem topic")
    difficulty: int = Field(..., ge=1, le=5, description="Problem difficulty (1-5)")
    estimated_time_to_solve_minutes: int = Field(..., ge=1, description="Estimated time to solve")


class ExecutorOutput(BaseModel):
    """Output from the executor."""
    selected_problems: List[SelectedProblem] = Field(default_factory=list, description="Problems selected for assessment")
    total_estimated_time: int = Field(..., ge=0, description="Total estimated time in minutes")
    
    class Config:
        json_schema_extra = {
            "example": {
                "selected_problems": [],
                "total_estimated_time": 45
            }
        }


class PlannerOutput(BaseModel):
    """Output from the planner."""
    assessment_plan: AssessmentPlan = Field(..., description="Generated assessment plan")
    reasoning_log: str = Field(..., description="Detailed reasoning from planner")
    
    class Config:
        json_schema_extra = {
            "example": {
                "assessment_plan": {
                    "strategy": "adaptive",
                    "topic_rules": [],
                    "time_limit_minutes": 60,
                    "reasoning_log": "Generated plan based on student profile"
                },
                "reasoning_log": "Detailed reasoning..."
            }
        }


class AssessmentResponse(BaseModel):
    """Response from assessment generation endpoint."""
    assessment_id: str = Field(..., description="Unique assessment identifier")
    planner_output: PlannerOutput = Field(..., description="Output from planner")
    executor_output: ExecutorOutput = Field(..., description="Output from executor")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Assessment creation timestamp")
    
    class Config:
        json_schema_extra = {
            "example": {
                "assessment_id": "assessment-123",
                "planner_output": {
                    "assessment_plan": {
                        "strategy": "adaptive",
                        "topic_rules": [],
                        "time_limit_minutes": 60,
                        "reasoning_log": "Generated plan"
                    },
                    "reasoning_log": "Detailed reasoning"
                },
                "executor_output": {
                    "selected_problems": [],
                    "total_estimated_time": 45
                },
                "created_at": "2024-01-01T00:00:00"
            }
        }

